# Herramientas computacionales para solucionar PDEs

### Juan S. Hincapié - Carlos Duque-Daza

## Bienvenidos a la segunda parte del curso

<div align='justify'>Hasta este momento del curso "sólo" hemos estudiado las ecuaciones diferenciales ordinarias... y digo "sólo" porque en realidad, detrás de esta primera parte hemos recorrido mucho camino: reforzamos los conceptos de adimensionalización, al igual que los principios de conservación de masa y de momento, también desarrollamos modelos para tanques interconectados, vaciado de tanques y sistemas mecánicos, y no olvidemos los conceptos de estabilidad. Pues bien, ya es hora de dar un paso más, ¿Cómo? Pues estudiando las ecuaciones diferenciales parciales (EDPs), sólo así podremos completar nuestra formación como modeladores matemáticos juniors. </div>
<br>

<div align='justify'>Para empezar con el pie derecho en esta segunda parte, debemos pasar primero por una capacitación. Así es: debemos aprender una serie de herramientas y técnicas de programación para no salir tan mal heridos de esta parte del curso. El contenido es el siguiente:</div>

1. Refuerzo vectores
1. Refuerzo matrices
1. ¿Cómo llenar una matriz que presenta un patrón?
1. Resolver sistema de ecuaciones lineales

$\color{RoyalBlue}{\LARGE{\textbf{Refuerzo de vectores}}}$

<div align='justify'>Los vectores, matrices y la operación entre ellos es esencial para la solución de modelos matemáticos ¿Qué nos ofrece Python para este aspecto? Pues bien tenemos la librería Numpy, una biblioteca que da soporte para crear vectores y matrices grandes multidimensionales, junto con una gran colección de funciones matemáticas de alto nivel para operar con ellas. Lo primero que debemos hacer es importarla. Echemosle un vistazo: </div>

In [2]:
import numpy as np

Podemos crear vectores y operar con ellos:

In [8]:
# Crear el vector de forma "tradicional"
vector1 = np.array([1, 2])

# ¿Será posible crear un vector con range?
vector2 = np.arange(2, 4)

# Sume los dos vectores
print(vector1 + vector2)

[3 5]


$\color{RoyalBlue}{\large{\textbf{Operaciones: producto punto y producto elemento por elemento}}}$

<div align='justify'>Cree dos vectores, $v_1$ y $v_2$ de $1\times 5$. Con estos dos vectores plantee las siguientes operaciones e imprima sus resultados: </div>

1. Haga la multiplicación elemento por elemento e imprima el resultado.
1. Haga el producto punto

In [16]:
vector1 = np.array(range(1, 6))
vector2 = np.array(range(6, 11))

print(vector1, vector2)  #Multiplicación elemento por elemento
suma = 0
for i in range(len(vector1)):
    suma += vector1[i] * vector2[i]
print(vector1 * vector2)
print(suma)  #Producto punto, o interno
print(vector1 @ vector2)
print(np.dot(vector1, vector2))

[1 2 3 4 5] [ 6  7  8  9 10]
[ 6 14 24 36 50]
130
130
130


$\color{RoyalBlue}{\large{\textbf{Ejercicio 01}}}$

<div align='justify'>Un fabricante de joyería de diseño tiene órdenes por dos anillos, tres pares de aretes, cinco prendedores y un collar. El fabricante estima que le llevará 1 hora de mano de obra hacer un anillo, 1 1/2 horas hacer un par de aretes, 21 hora para un prendedor y 2 horas para un collar.</div>


1. Exprese las órdenes del fabricante como un vector fila.
1. Exprese los requerimientos en horas para los distintos tipos de joyas como un vector fila.
1. Utilice el producto punto para calcular el número total de horas que requerirá paraterminar las órdenes.
1. Utilize el producto elemento por elemento para calcular el tiempo que tarda en fabricar cada uno de los productos, es decir, cuánto tarda en producir los dos anillos, cuánto demora en los tres pares de aretes... etc.

In [21]:
objects = ["anillos","aretes","prendedores","collar"]
orders = np.array([2, 3, 5, 1])
factory_time = np.array([1, 1.5, 21, 2])
print(f"El tiempo necesitado final es de: {(orders @factory_time):.1f}")
for i in range(len(orders)):
    print(f"El tiempo necesario para realizar la cantidad de {orders[i]} {objects[i]} es de {(orders[i] * factory_time[i]):.2f} Horas")

El tiempo necesitado final es de: 113.5
El tiempo necesario para realizar la cantidad de 2 anillos es de 2.00 Horas
El tiempo necesario para realizar la cantidad de 3 aretes es de 4.50 Horas
El tiempo necesario para realizar la cantidad de 5 prendedores es de 105.00 Horas
El tiempo necesario para realizar la cantidad de 1 collar es de 2.00 Horas


$\color{RoyalBlue}{\large{\textbf{Ejercicio 02}}}$

<div align='justify'>Un turista regresó de un viaje por América del Sur con divisa extranjera de las siguientes denominaciones: 1000 pesos argentinos, 20 reales de Brasil, 100 pesos colombianos, 5000 pesos chilenos y 50 colones de Costa Rica. En dólares, un peso argentino valía $\$$0.3174, los reales brasileños $\$$0.4962, los pesos colombianos $\$$0.000471, los pesos chilenos $\$$0.00191 y los colones $\$$0.001928.</div>



1. Exprese la cantidad de cada tipo de moneda por medio de un vector fila
1. Exprese el valor de cada tipo de moneda en dólares por medio de un vector fila.
1. Utilice el producto escalar para calcular cuántos dólares valía el dinero extranjero del
turista

In [23]:
money = np.array([1000, 20, 100, 5000, 50])
dollars_convertions = np.array([0.3174, 0.4962, 0.000471, 0.00191, 0.001928])
print(f"El valor total del dinero en dolares es de: {money @ dollars_convertions:.2f}")

El valor total del dinero en dolares es de: 337.02


$\color{RoyalBlue}{\large{\textbf{Llamar elementos de un vector}}}$

<div align='justify'> Cree un vector que tenga los números enteros desde el 1 hasta el 5.</div>


In [47]:
vector1 = np.arange(1, 6)
print(vector1)

[1 2 3 4 5]


<div align='justify'>¿Cómo haría para llamar al primer elemento del vector?</div>


In [48]:
vector1[0]

np.int64(1)

<div align='justify'>¿Y cómo llamaría al último elemento del vector?</div>


In [49]:
vector1[-1]

np.int64(5)

También podemos conocer el número de elementos que contiene un vector usando la siguiente función:

In [50]:
print(len(vector1))
vector_fila = np.array([[1, 2, 3, 4, 5]])
print(vector1.shape) #maleable
print(vector_fila.shape) 
print(vector_fila.T.shape) #COlumna .T transpuesta

5
(5,)
(1, 5)
(5, 1)


$\color{RoyalBlue}{\large{\textbf{Ejercicio 03}}}$
<div align='justify'> Escriba un código en el que se solicita 5 número a un usuario y se deben almacenar en un vector. Al final se debe imprimir el vector.</div>



In [55]:
#Esta función nos permite reservar memoria para el vector, creando un vector de ceros:
n = 5
vect = np.array([np.zeros(n)])
print(vect.shape, vect)
for i in range(n):
    vect[0][i] = float(input(f"Digite el número deseado en la posición {i+1} de su vector"))
print(vect)
    

(1, 5) [[0. 0. 0. 0. 0.]]


Digite el número deseado en la posición 1 de su vector 1
Digite el número deseado en la posición 2 de su vector 2
Digite el número deseado en la posición 3 de su vector 3
Digite el número deseado en la posición 4 de su vector 4
Digite el número deseado en la posición 5 de su vector 5


[[1. 2. 3. 4. 5.]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 04}}}$

<div align='justify'> Escribe un programa que muestre sólo aquellos números de una lista que cumplan las siguientes condiciones:</div>

1. El número debe ser divisible por cinco
1. El número debe ser mayor a 50.
1. El número debe ser menor a 500

In [65]:
numeros = np.array([12, 75, 150, 180, 145, 525, 50])
#Debemos iterar sobre los número de la lista. 
#Propongo una manera:
filtros = numeros[(numeros % 5 == 0) & (numeros > 50) & (numeros < 500)] # nueva forma !!!
for i in range(len(numeros)):
    if numeros[i] % 5 == 0 and numeros[i] > 50 and numeros[i] < 500:
        print(f"Número que cumple con las condiciones {numeros[i]}")
print(filtros)

Número que cumple con las condiciones 75
Número que cumple con las condiciones 150
Número que cumple con las condiciones 180
Número que cumple con las condiciones 145
[ 75 150 180 145]


In [71]:
numeros = np.array([[12, 75, 150, 180, 145, 525, 50]])
#Debemos iterar sobre los número de la lista. 
#Propongo una manera:
filtros = numeros[0][(numeros[0] % 5 == 0) & (numeros[0] > 50) & (numeros[0] < 500)] # nueva forma !!!
for i in range(len(numeros[0])):
    if numeros[0][i] % 5 == 0 and numeros[0][i] > 50 and numeros[0][i] < 500:
        print(f"Número que cumple con las condiciones {numeros[0][i]}")
print(filtros)

Número que cumple con las condiciones 75
Número que cumple con las condiciones 150
Número que cumple con las condiciones 180
Número que cumple con las condiciones 145
[ 75 150 180 145]


$\color{RoyalBlue}{\LARGE{\textbf{Refuerzo matrices}}}$


<div align='justify'> Miremos como se puede crear una matriz:</div>

In [67]:
M = np.array([[3,4,-1],[2,0,1],[1,3,-2]])
print(M)

[[ 3  4 -1]
 [ 2  0  1]
 [ 1  3 -2]]


$\color{RoyalBlue}{\large{\textbf{Operaciones con matrices}}}$
<div align='justify'> Podemos sacar la inversa de la matriz:</div>

In [72]:
M_inv = np.linalg.inv(M)
print(M_inv)

# ¿Cómo verificamos que es la inversa?
print(M @ M_inv)

[[-0.6  1.   0.8]
 [ 1.  -1.  -1. ]
 [ 1.2 -1.  -1.6]]
[[ 1.00000000e+00 -3.33066907e-16 -2.22044605e-16]
 [ 2.22044605e-16  1.00000000e+00 -4.44089210e-16]
 [ 0.00000000e+00 -2.22044605e-16  1.00000000e+00]]


In [109]:
M_tr = np.transpose(M)
print(M_tr)
# ¿Cómo verificamos que es la transpuesta?
for i in range(len(M[0])):
    for j in range(3):
        print(M_tr[j][i] == M[i][j])

[[ 3  2  1]
 [ 4  0  3]
 [-1  1 -2]]
True
True
True
True
True
True
True
True
True


In [20]:
#¿Será que el determinante es diferente de cero? ¿Cómo saberlo?
M_det = np.linalg.det(M)
print(M_det)

5.000000000000003


$\color{RoyalBlue}{\large{\textbf{Ejercicio 05}}}$

<div align='justify'>Una fábrica de muebles de calidad tiene dos divisiones: un taller de máquinas herramienta donde se fabrican las partes de los muebles, y una división de ensamble y terminado en la que se unen las partes para obtener el producto final. Suponga que se tienen $12$ empleados en el taller y $20$ en la división y que cada empleado trabaja $8$ horas. Suponga también que se producen únicamente dos artículos: sillas y mesas. Una silla requiere $384/17$ horas de maquinado y $480/17$ horas de ensamble y terminado. Una mesa requiere $240/17$ horas de maquinado y $640/17$ horas de ensamble y terminado. Suponiendo que se tiene una demanda ilimitada de estos productos y que el fabricante desea mantener ocupados a todos sus empleados, ¿cuántas sillas y cuántas mesas puede producir esta fábrica al día? </div>

$x$: Número de sillas $y$: Número de mesas

\begin{align*}
    & \frac{384}{17}x + \frac{240}{17}y = 8 \times 12 \\
    & \frac{480}{17}x + \frac{640}{17}y = 8 \times 20
\end{align*}

Con las funciones que hemos visto hasta ahora, ¿Cómo podríamos resolver este problema?

In [87]:
A = np.array([[384, 240],[480,640]]) * 1/17
b = np.array([[8 * 12], [8 * 20]])
print(np.linalg.solve(A, b))

[[3.]
 [2.]]


In [89]:
A = np.array([[384, 240],[480,640]]) * 1/17
b = np.array([[8 * 12], [8 * 20]])
A_inv = np.linalg.inv(A)
x = A_inv @ b
print(x)

[[3.]
 [2.]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 06}}}$

<div align='justify'>La alacena de ingredientes mágicos de una hechicera contiene $10$ onzas de tréboles de
cuatro hojas molidos y $14$ onzas de raíz de mandrágora en polvo. La alacena se resurte en forma automática siempre y cuando ella termine con todo lo que tiene. Una poción para entender Python requiere $3 \frac{1}{13}$ onzas de tréboles y $2~\frac{2}{13}$ onzas de mandrágora. Una receta de un conocido tratamiento para poder plantear modelos matemáticos como Alfio Quarteroni   requiere $5~\frac{5}{13}$ onzas de tréboles y $10~\frac{10}{13}$ onzas de mandrágora. ¿Qué cantidad de la poción para entender Python y del remedio para modelar matemáticamente se debe combinar para usar toda la reserva en su alacena?</div>

$x$: poción para enteder Python $y$: poción para plantear modelos matemáticos

\begin{align*}
    & \frac{40}{13}x + \frac{70}{13}y = 10 \\
    & \frac{28}{13}x + \frac{140}{13}y = 14
\end{align*}


In [96]:
A = np.array([[40, 70],[28, 140]]) * 1 / 13
b = np.array([[10], [14]])
A_inv = np.linalg.inv(A)
x = A_inv @ b
print(f"Sistema Ax = b {A} {x} = {b}")
print(x)

Sistema Ax = b [[ 3.07692308  5.38461538]
 [ 2.15384615 10.76923077]] [[1.5]
 [1. ]] = [[10]
 [14]]
[[1.5]
 [1. ]]


¿ Cómo verifica que el resultado es el correcto?

[[10.]
 [14.]]


$\color{RoyalBlue}{\LARGE{\textbf{¿Cómo llenar una matriz que presenta un patrón?}}}$

$\color{RoyalBlue}{\large{\textbf{Índices de una matriz}}}$


<div align='justify'>Los elementos de una matriz, al igual que con los vectores, tienen unos índices que los indentifican ¿Cuál es la lógica de los índices?</div>


In [123]:
F = np.array([[1,2,3],[4,5,6],[7,8,9]])
print(F)
A = np.zeros([3, 3])
for i in range(3):
    for j in range(3):
        A[i][j] = 3*i + j + 1
print(A)

[[1 2 3]
 [4 5 6]
 [7 8 9]]
[[1. 2. 3.]
 [4. 5. 6.]
 [7. 8. 9.]]


In [106]:
print(F[0,0])

1


In [107]:
print(F[2,2]) #¿Por qué no es F[3,3]?

9


¿De qué otra manera se podría imprimir el último elemento de la matriz?

In [108]:
F[-1,-1]

np.int64(9)

¿Qué haría para imprimir toda la segunda fila de la matriz F?

In [113]:
F[1]

array([4, 5, 6])

¿Qué haría para imprimir únicamente la segunda columna?

In [129]:
F[:,1]

array([2, 5, 8])

¿Será lo mismo emplear $F[1,:-1]$ que $F[1,:]$?

In [122]:
F[1:-1] == F[1:]

array([[ True,  True,  True],
       [False, False, False]])

$\color{RoyalBlue}{\large{\textbf{Ciclo for para recorrer la matriz}}}$

<div align='justify'>Saber cómo ingresar en las "entrañas" es muy importante para poder implementar métodos númericos en código. Por ejemplo, para ingresar condiciones de frontera de una EDP. Por ahora, nos esforzaremos por "agarrar" la lógica de los recorridos usando ciclos For.</div>

In [112]:
H = np.array([[1,2,3],[4,5,6],[7,8,9]])*1.5
print(H)

[[ 1.5  3.   4.5]
 [ 6.   7.5  9. ]
 [10.5 12.  13.5]]


Tenemos muchas opciones para recorrer una matriz; pero acá les voy a presentar únicamente una. Si entendemos esta primera lógica, entender las demás será "papita pal loro."

In [93]:
#Podemos obtener primero las dimensiones de una matriz con la siguiente función
row, col = H.shape
#Construimos un primer ciclo for que irá fila por fila
for r in range(0,row,1):
    #Pero antes de pasar a la siguiente fila, tendrá que pasar por todas las columnas
    for c in range(0,col,1):
        #¿Cómo saber si estamos recorriendo la matriz como pensábamos? ¡Print!
        print(H[r, c], end = " ")
    print("")

1.5 3.0 4.5 
6.0 7.5 9.0 
10.5 12.0 13.5 


$\color{RoyalBlue}{\large{\textbf{Identificar patrón}}}$

<div align='justify'> Los sistemas de ecuaciones que surgen en las soluciones numéricas de las EDPs unidimensionales presentan matrices con patrones que se identifican a simple vista. Es importantísimo llenar la matriz siguiendo dicho patrón con el fin de resolver dicho sistema computacionalmente. </div>


$\color{RoyalBlue}{\large{\textbf{Ejercicio 07:}}}$

Obtener el siguiente llenado de matriz usando ciclos for:

$$
    B={\left(\begin{array}{l l l}
    {1}&{0}&{0}\\ 
    {0}&{1}&{0}\\ 
    {0}&{0}&{1}
    \end{array}\right)}
$$


In [143]:
B = np.zeros((3,3), dtype = int)
print(B)

[[0 0 0]
 [0 0 0]
 [0 0 0]]


In [144]:
row, col = B.shape
for i in range(row):
    for j in range(col):
        if  i == j:
            B[i, j] = 1
print(B)

[[1 0 0]
 [0 1 0]
 [0 0 1]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 08: semi - legendario}}}$

Obtener el siguiente llenado de matriz usando ciclos for:

$$
    B={\left(\begin{array}{l l l l l}
    {0}&{1}&{0}&{0}&{0}\\ 
    {1}&{0}&{1}&{0}&{0}\\ 
    {0}&{1}&{0}&{1}&{0}\\
    {0}&{0}&{1}&{0}&{1}\\
    {0}&{0}&{0}&{1}&{0}
    \end{array}\right)}
$$

In [154]:
S = np.zeros((5,5), dtype = int)
row, col = S.shape
for i in range(row):
    for j in range(col):
        if i == j + 1 or j == i + 1:
            S[i, j] = 1
print(S)

[[0 1 0 0 0]
 [1 0 1 0 0]
 [0 1 0 1 0]
 [0 0 1 0 1]
 [0 0 0 1 0]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 09: semi - plus - legendario}}}$

Obtener el siguiente llenado de matriz usando ciclos for:

$$
    B={\left(\begin{array}{l l l l l}
    {5}&{1}&{0}&{2}&{0}\\ 
    {1}&{5}&{1}&{0}&{2}\\ 
    {0}&{1}&{5}&{1}&{0}\\
    {2}&{0}&{1}&{5}&{1}\\
    {0}&{2}&{0}&{1}&{5}
    \end{array}\right)}
$$

In [156]:
S = np.zeros((5,5), dtype = int)
row, col = S.shape
for i in range(row):
    for j in range(col):
        if i == j:
            S[i, j] = 5
        elif i == j + 1 or j == i+1:
            S[i, j] = 1
        elif j == 3 + i or i == 3 + j:
            S[i, j]  = 2
print(S)

[[5 1 0 2 0]
 [1 5 1 0 2]
 [0 1 5 1 0]
 [2 0 1 5 1]
 [0 2 0 1 5]]


$\color{RoyalBlue}{\large{\textbf{Ejercicio 10: legendario}}}$

Obtener el siguiente llenado de matriz usando ciclos for:

$$
    B={\left(\begin{array}{l l l l l}
    {1}&{2}&{2}&{2}&{2}\\ 
    {2}&{1}&{0}&{0}&{2}\\ 
    {2}&{0}&{1}&{0}&{2}\\
    {2}&{0}&{0}&{1}&{2}\\
    {2}&{2}&{2}&{2}&{1}
    \end{array}\right)}
$$


In [160]:
S = np.zeros((5,5), dtype = int)
row, col = S.shape
for i in range(row):
    for j in range(col):
        if i == j:
            S[i, j] = 1
        elif j == 0 or i == 0:
            S[i, j] = 2
        elif j == row - 1 or i == row - 1:
            S[i, j] = 2
print(S)
#Plantealo con vectorizacion?

[[1 2 2 2 2]
 [2 1 0 0 2]
 [2 0 1 0 2]
 [2 0 0 1 2]
 [2 2 2 2 1]]


$\color{RoyalBlue}{\LARGE{\textbf{Resolver sistema de ecuaciones lineales}}}$

$\color{RoyalBlue}{\large{\textbf{Ejercicio 11: }}}$

$$
\left[\begin{array}{rrrrr}
375 & -125 & 0 & 0 & 0 \\
-125 & 250 & -125 & 0 & 0 \\
0 & -125 & 250 & -125 & 0 \\
0 & 0 & -125 & 250 & -125 \\
0 & 0 & 0 & -125 & 375
\end{array}\right]\left[\begin{array}{l}
T_1 \\
T_2 \\
T_3 \\
T_4 \\
T_5
\end{array}\right]=\left[\begin{array}{r}
29000 \\
4000 \\
4000 \\
4000 \\
54000
\end{array}\right]
$$


Este debería ser el resultado:

$$
\left[\begin{array}{l}
T_1 \\
T_2 \\
T_3 \\
T_4 \\
T_5
\end{array}\right]=\left[\begin{array}{l}
150 \\
218 \\
254 \\
258 \\
230
\end{array}\right]
$$

In [173]:
S = np.zeros((5,5), dtype = int)
row, col = S.shape
for i in range(row):
    for j in range(col):
        if i == j and i != 0 and i != 0 and i != row-1 and i != row-1 :
            S[i, j] = 250
        elif (j == 0 and i == 0) or (j == row-1 and i == row -1):
            S[i, j] = 375
        elif i == j + 1 or j == i + 1:
            S[i, j] = -125
print(S)
b = np.array([[2.9e4], [4e3], [4e3], [4e3], [5.4e4]])

[[ 375 -125    0    0    0]
 [-125  250 -125    0    0]
 [   0 -125  250 -125    0]
 [   0    0 -125  250 -125]
 [   0    0    0 -125  375]]


In [176]:
print(f"Nuestra solución es \n {np.linalg.solve(S, b).T}")

Nuestra solución es 
 [[150. 218. 254. 258. 230.]]


In [177]:
# MÁS FÁCIL

In [179]:
S = np.zeros((5,5), dtype = int)
row, col = S.shape
for i in range(row):
    for j in range(col):
        if i == j and i != 0:
            S[i, j] = 250
        elif i == j + 1:
            S[i, j] = -125
            S[j, i] = -125
S[0, 0] = 375
S[-1, -1] = 375
print(S)
b = np.array([[2.9e4], [4e3], [4e3], [4e3], [5.4e4]])

[[ 375 -125    0    0    0]
 [-125  250 -125    0    0]
 [   0 -125  250 -125    0]
 [   0    0 -125  250 -125]
 [   0    0    0 -125  375]]


In [180]:
print(f"Nuestra solución es \n {np.linalg.solve(S, b).T}")

Nuestra solución es 
 [[150. 218. 254. 258. 230.]]
